
// This file has been generated by the GUI designer. Do not modify.
namespace RepoSync.GuiGtk.Widgets
{
	public partial class SyncActionWidget
	{
		protected virtual void Build ()
		{
			global::Stetic.Gui.Initialize (this);
			// Widget RepoSync.GuiGtk.Widgets.SyncActionWidget
			global::Stetic.BinContainer.Attach (this);
			this.Name = "RepoSync.GuiGtk.Widgets.SyncActionWidget";
			if ((this.Child != null)) {
				this.Child.ShowAll ();
			}
			this.Hide ();
		}
	}
}
